# Generated by Django 3.1 on 2020-08-20 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExlFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя файла')),
                ('xlfile', models.FileField(upload_to='xlfiles', verbose_name='Файл Excel')),
                ('status', models.CharField(choices=[('loaded', 'Загружено'), ('is_processed', 'Обрабатывается'), ('processed', 'Обработано')], default='loaded', max_length=15, verbose_name='Статус документа')),
                ('date_load', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время загрузки файла')),
                ('date_end_proc', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания обработки файла')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Результат обработки файла')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец файла')),
            ],
            options={
                'verbose_name': 'Документ excel',
                'verbose_name_plural': 'Документ excel',
            },
        ),
    ]
